# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres            # Utilizza il nome dell'utente di postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>   # Usa la variabile d'ambiente per la password
  host: localhost               # Host locale
  port: 5432                    # Porta di default
  # Puoi aggiungere altre configurazioni se necessario

development:
  <<: *default
  database: stampa3d_shop_development

test:
  <<: *default
  database: stampa3d_shop_test

production:
  primary: &primary_production
    <<: *default
    database: stampa3d_shop_production
    username: postgres          # Usa l'utente postgres per produzione
    password: <%= ENV["DATABASE_PASSWORD"] %>  # Usa la variabile d'ambiente per la password
  cache:
    <<: *primary_production
    database: stampa3d_shop_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stampa3d_shop_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: stampa3d_shop_production_cable
    migrations_paths: db/cable_migrate
